<a href="https://colab.research.google.com/github/jonnythebard/tf2_workbook/blob/master/text_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# imports
try:
  %tensorflow_version 2.x  # Colab only.
except Exception:
  pass

import tensorflow as tf
print(tf.__version__)

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

`%tensorflow_version` only switches the major version: `1.x` or `2.x`.
You set: `2.x  # Colab only.`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.
2.0.0


In [0]:
sentences = [
  "I like eggs and ham.",
  "I love chocolates and bunnies",
  "I hate onions."
]

In [3]:
MAX_VOCAB_SIZE = 20000
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

print(sequences)
print(tokenizer.word_index)

[[1, 3, 4, 2, 5], [1, 6, 7, 2, 8], [1, 9, 10]]
{'i': 1, 'and': 2, 'like': 3, 'eggs': 4, 'ham': 5, 'love': 6, 'chocolates': 7, 'bunnies': 8, 'hate': 9, 'onions': 10}


In [4]:
MAX_SEQUENCE_LENGTH = 5
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)
# data = pad_sequences(sequences, maxlen=6) # padding
# data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH, padding="post")
# data = pad_sequences(sequences, maxlen=4) # truncation
# data = pad_sequences(sequences, maxlen=4, truncating="post")

print(data)

[[ 1  3  4  2  5]
 [ 1  6  7  2  8]
 [ 0  0  1  9 10]]
